language: objective-c
osx_image: xcode9.3


env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8
before_install:
  - rvm install ruby-2.2.2
  - gem install cocoapods
  - gem install xcpretty -N
  - brew update
  - brew install swiftlint || true
script:
  - set -o pipefail
  - pod install
  - xcodebuild -workspace Telemac.xcworkspace -scheme Telemac ONLY_ACTIVE_ARCH=NO | xcpretty -c
  - swiftlint
